# Databricks deployment input file
# Define per-environment customer, catalog, and schema names

environments:
  dev:
    customer: PANDs
    catalog: rio_cicd_setup_dev
    schemas:
      - inventory
      - masterdata
  sit:
    customer: TBD
    catalog: rio_cicd_setup_sit
    schemas:
      - inventory
      - masterdata
  uat:
    customer: TBD
    catalog: rio_cicd_setup_uat
    schemas:
      - inventory
      - masterdata
  prod:
    customer: TBD
    catalog: rio_cicd_setup_prod
    schemas:
      - inventory
      - masterdata


